routes:
  - persons
  - pets
relationships:
  pets:
    - relatedRoute: persons
      foreignKey: ownerIds
persons:
  - id: 1
    name: Jan
  - id: 2
    name: Sofie
  - id: 3
    name: Tim
  - name: wout
    id: 4
  - name: oranoos
    id: 5
  - name: Eyad
    id: 6
pets:
  - id: 1
    type: dog
    name: Jimmy
    ownerIds:
      - 2
  - id: 2
    type: cat
    name: Duvel
    ownerIds:
      - 1
      - 2
